version: "3.8"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    command: '/bin/sh -c ''while :; do sleep 336h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - core
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - private-network

  core:
    container_name: core
    image: core:latest-full
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      context: .
      dockerfile: core.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    networks:
      - private-network

  postgres:
    container_name: postgres
    image: postgres:12
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    networks:
      - private-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 7000:7000
    networks:
      - private-network
    logging:
        driver: none

networks:
  private-network:
    driver: bridge
