export const USER_MENU_OPEN = 'USER_MENU_OPEN';
export const USER_MENU_CLOSE = 'USER_MENU_CLOSE';
export const USER_MENU_CHANGE_STATE = 'USER_MENU_CHANGE_STATE';
export const ACTIVATE_POPUP = 'ACTIVATE_POPUP';
export const DEACTIVATE_POPUP = 'DEACTIVATE_POPUP';
export const GET_CONTENT_TYPE = 'GET_CONTENT_TYPE';

